# Generated by Django 2.1.2 on 2018-12-22 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20181221_0234'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='first_time',
            field=models.BooleanField(default=True),
        ),
    ]
